name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node js
      uses: actions/setup-node@v6
      with: 
        node-version: 22
        cache: 'yarn'
    - run: yarn --frozen-lockfile

    - name: Build
      run: yarn tauri:build
